services:
  streamlit:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-analysis-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    volumes:
      - ./frontend:/app
    command: streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0

networks:
  default:
    name: stock-analysis-network