services:
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-analysis-celery:latest
    container_name: stock-analysis-celery-worker
    expose:
      - "9808"
    environment:
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - CELERY_METRICS_PORT=${CELERY_METRICS_PORT}
      - STOCK_ANALYSIS_DB=${STOCK_ANALYSIS_DB}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - FRED_API_KEY=${FRED_API_KEY}
    volumes:
      - ./app:/app/app
      - ./data:/data
    command: celery -A app.main worker --loglevel=info

  celery-beat:
    image: stock-analysis-celery:latest
    container_name: stock-analysis-celery-beat
    environment:
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - STOCK_ANALYSIS_DB=${STOCK_ANALYSIS_DB}
      - FRED_API_KEY=${FRED_API_KEY}
    volumes:
      - ./app:/app/app
    command: celery -A app.main beat --loglevel=info

  flower:
    image: stock-analysis-celery:latest
    container_name: stock-analysis-flower
    environment:
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
      - STOCK_ANALYSIS_DB=${STOCK_ANALYSIS_DB}
      - FLOWER_UNAUTHENTICATED_API=${FLOWER_UNAUTHENTICATED_API}
      - FRED_API_KEY=${FRED_API_KEY}
    volumes:
      - ./app:/app/app
    ports:
      - "5555:5555"
    command: celery -A app.main flower --port=5555 --prometheus_metrics

  celery-exporter:
    image: danihodovic/celery-exporter:latest
    container_name: stock-analysis-celery-exporter
    ports:
      - "9808:9808"
    environment:
      - CE_BROKER_URL=${REDIS_URL}
      - CE_ENABLE_EVENTS=true
    restart: unless-stopped

networks:
  default:
    name: stock-analysis-network
    external: true