services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-analysis-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - STOCK_ANALYSIS_DB=${STOCK_ANALYSIS_DB}
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - stock-analysis-network

networks:
  stock-analysis-network:
    external: true