stock_data = [
    {
        "ticker": "AAPL",
        "timestamp": "2025-01-24T10:00:00Z",
        "sentiment_score": 0.42,
        "mention_count": 23,
        "positive_mentions": 12,
        "negative_mentions": 11,
        "neutral_mentions": 0,
        "avg_upvotes": 15.2,
        "subreddit_breakdown": {"stocks": 12, "investing": 8, "wallstreetbets": 3},
        "avg_comment_count": 8.5,
    },
    {
        "ticker": "AAPL",
        "timestamp": "2025-01-24T11:00:00Z",
        "sentiment_score": 0.58,
        "mention_count": 34,
        "positive_mentions": 22,
        "negative_mentions": 12,
        "neutral_mentions": 0,
        "avg_upvotes": 18.7,
        "subreddit_breakdown": {"stocks": 15, "investing": 12, "wallstreetbets": 7},
        "avg_comment_count": 11.3,
    },
    {
        "ticker": "AAPL",
        "timestamp": "2025-01-24T12:00:00Z",
        "sentiment_score": 0.71,
        "mention_count": 51,
        "positive_mentions": 39,
        "negative_mentions": 12,
        "neutral_mentions": 0,
        "avg_upvotes": 24.1,
        "subreddit_breakdown": {"stocks": 22, "investing": 18, "wallstreetbets": 11},
        "avg_comment_count": 15.8,
    },
    {
        "ticker": "GME",
        "timestamp": "2025-01-24T10:00:00Z",
        "sentiment_score": 0.78,
        "mention_count": 89,
        "positive_mentions": 71,
        "negative_mentions": 18,
        "neutral_mentions": 0,
        "avg_upvotes": 142.3,
        "subreddit_breakdown": {"wallstreetbets": 67, "superstonk": 15, "stocks": 7},
        "avg_comment_count": 34.2,
    },
    {
        "ticker": "GME",
        "timestamp": "2025-01-24T11:00:00Z",
        "sentiment_score": 0.82,
        "mention_count": 112,
        "positive_mentions": 95,
        "negative_mentions": 17,
        "neutral_mentions": 0,
        "avg_upvotes": 156.7,
        "subreddit_breakdown": {"wallstreetbets": 84, "superstonk": 19, "stocks": 9},
        "avg_comment_count": 41.5,
    },
    {
        "ticker": "GME",
        "timestamp": "2025-01-24T12:00:00Z",
        "sentiment_score": 0.69,
        "mention_count": 97,
        "positive_mentions": 68,
        "negative_mentions": 29,
        "neutral_mentions": 0,
        "avg_upvotes": 134.2,
        "subreddit_breakdown": {"wallstreetbets": 71, "superstonk": 18, "stocks": 8},
        "avg_comment_count": 38.9,
    },
    {
        "ticker": "HOOD",
        "timestamp": "2025-01-24T10:00:00Z",
        "sentiment_score": 0.31,
        "mention_count": 18,
        "positive_mentions": 7,
        "negative_mentions": 11,
        "neutral_mentions": 0,
        "avg_upvotes": 8.4,
        "subreddit_breakdown": {"wallstreetbets": 12, "stocks": 4, "investing": 2},
        "avg_comment_count": 6.1,
    },
    {
        "ticker": "HOOD",
        "timestamp": "2025-01-24T11:00:00Z",
        "sentiment_score": 0.28,
        "mention_count": 24,
        "positive_mentions": 8,
        "negative_mentions": 16,
        "neutral_mentions": 0,
        "avg_upvotes": 7.2,
        "subreddit_breakdown": {"wallstreetbets": 17, "stocks": 5, "investing": 2},
        "avg_comment_count": 5.8,
    },
    {
        "ticker": "HOOD",
        "timestamp": "2025-01-24T12:00:00Z",
        "sentiment_score": 0.35,
        "mention_count": 21,
        "positive_mentions": 9,
        "negative_mentions": 12,
        "neutral_mentions": 0,
        "avg_upvotes": 9.1,
        "subreddit_breakdown": {"wallstreetbets": 14, "stocks": 5, "investing": 2},
        "avg_comment_count": 6.7,
    },
    {
        "ticker": "SOFI",
        "timestamp": "2025-01-24T10:00:00Z",
        "sentiment_score": 0.64,
        "mention_count": 42,
        "positive_mentions": 29,
        "negative_mentions": 13,
        "neutral_mentions": 0,
        "avg_upvotes": 31.5,
        "subreddit_breakdown": {"wallstreetbets": 25, "stocks": 12, "investing": 5},
        "avg_comment_count": 12.3,
    },
    {
        "ticker": "SOFI",
        "timestamp": "2025-01-24T11:00:00Z",
        "sentiment_score": 0.71,
        "mention_count": 56,
        "positive_mentions": 42,
        "negative_mentions": 14,
        "neutral_mentions": 0,
        "avg_upvotes": 38.2,
        "subreddit_breakdown": {"wallstreetbets": 34, "stocks": 16, "investing": 6},
        "avg_comment_count": 15.7,
    },
    {
        "ticker": "SOFI",
        "timestamp": "2025-01-24T12:00:00Z",
        "sentiment_score": 0.68,
        "mention_count": 49,
        "positive_mentions": 35,
        "negative_mentions": 14,
        "neutral_mentions": 0,
        "avg_upvotes": 35.8,
        "subreddit_breakdown": {"wallstreetbets": 29, "stocks": 14, "investing": 6},
        "avg_comment_count": 14.2,
    },
    {
        "ticker": "RKLB",
        "timestamp": "2025-01-24T10:00:00Z",
        "sentiment_score": 0.88,
        "mention_count": 67,
        "positive_mentions": 61,
        "negative_mentions": 6,
        "neutral_mentions": 0,
        "avg_upvotes": 87.3,
        "subreddit_breakdown": {"wallstreetbets": 38, "stocks": 18, "space": 11},
        "avg_comment_count": 22.4,
    },
    {
        "ticker": "RKLB",
        "timestamp": "2025-01-24T11:00:00Z",
        "sentiment_score": 0.92,
        "mention_count": 83,
        "positive_mentions": 78,
        "negative_mentions": 5,
        "neutral_mentions": 0,
        "avg_upvotes": 94.7,
        "subreddit_breakdown": {"wallstreetbets": 47, "stocks": 23, "space": 13},
        "avg_comment_count": 26.8,
    },
    {
        "ticker": "RKLB",
        "timestamp": "2025-01-24T12:00:00Z",
        "sentiment_score": 0.85,
        "mention_count": 71,
        "positive_mentions": 63,
        "negative_mentions": 8,
        "neutral_mentions": 0,
        "avg_upvotes": 89.2,
        "subreddit_breakdown": {"wallstreetbets": 41, "stocks": 19, "space": 11},
        "avg_comment_count": 24.1,
    },
]
