CREATE TABLE post_no_preference_option_chain (
    id SERIAL PRIMARY KEY,
    date DATE,
    ticker VARCHAR(10),
    expiration DATE,
    strike DECIMAL(10, 2),
    call_put VARCHAR(4),
    bid DECIMAL(10, 2),
    ask DECIMAL(10, 2),
    vol DECIMAL(6, 4),
    delta DECIMAL(6, 4),
    gamma DECIMAL(6, 4),
    theta DECIMAL(6, 4),
    vega DECIMAL(6, 4),
    rho DECIMAL(6, 4),

    UNIQUE(date, ticker, expiration, strike, call_put)
);

CREATE TABLE spy_eod_options (
    id SERIAL PRIMARY KEY,
    quote_read_time TIMESTAMPTZ,
    underlying_last DECIMAL(10, 2),
    expire_date DATE,
    dte DECIMAL(10, 2),
    c_delta DECIMAL(10, 6),
    c_gamma DECIMAL(10, 6),
    c_vega DECIMAL(10, 6),
    c_theta DECIMAL(10, 6),
    c_rho DECIMAL(10, 6),
    c_iv DECIMAL(10, 6),
    c_volume INTEGER,
    c_last DECIMAL(10, 2),
    c_size VARCHAR(50),
    c_bid DECIMAL(10, 2),
    c_ask DECIMAL(10, 2),
    strike DECIMAL(10, 2),
    p_bid DECIMAL(10, 2),
    p_ask DECIMAL(10, 2),
    p_size VARCHAR(50),
    p_last DECIMAL(10, 2),
    p_delta DECIMAL(10, 6),
    p_gamma DECIMAL(10, 6),
    p_vega DECIMAL(10, 6),
    p_theta DECIMAL(10, 6),
    p_rho DECIMAL(10, 6),
    p_iv DECIMAL(10, 6),
    p_volume INTEGER,
    strike_distance DECIMAL(10, 2),
    strike_distance_pct DECIMAL(4, 3)
);

CREATE TABLE td_eod_options (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10),
    quote_date DATE,
    expiration DATE,
    strike DECIMAL(10, 4),
    call_put VARCHAR(4),
    underlying_price DECIMAL(10, 2),
    open DECIMAL(10, 2),
    high DECIMAL(10, 2),
    low DECIMAL(10, 2),
    close DECIMAL(10, 2),
    volume INTEGER,
    bid DECIMAL(10, 2),
    ask DECIMAL(10, 2),
    delta DECIMAL(8, 6),
    gamma DECIMAL(8, 6),
    theta DECIMAL(8, 6),
    vega DECIMAL(8, 6),
    rho DECIMAL(8, 6),
    implied_vol FLOAT,
    iv_error FLOAT,
    d1 FLOAT,
    d2 FLOAT,
    color DECIMAL(8, 6),
    zomma DECIMAL(8, 6),
    speed DECIMAL(8, 6),
    epsilon DECIMAL(8, 6),
    lambda DECIMAL(8, 6),
    vomma DECIMAL(8, 6),
    vera DECIMAL(8, 6),
    veta DECIMAL(8, 6),
    ultima DECIMAL(8, 6),
    charm DECIMAL(8, 6),
    vanna DECIMAL(8, 6),
    dual_delta DECIMAL(8, 6),
    dual_gamma DECIMAL(8, 6),

    UNIQUE(quote_date, ticker, expiration, strike, call_put)
);

CREATE INDEX idx_td_eod_options_covering
ON td_eod_options(ticker, call_put, quote_date)
INCLUDE (underlying_price, expiration, strike, bid, ask, delta);
