CREATE TABLE post_no_preference_option_chain (
    id SERIAL PRIMARY KEY,
    date DATE,
    ticker VARCHAR(10),
    expiration DATE,
    strike DECIMAL(10, 2),
    call_put VARCHAR(4),
    bid DECIMAL(10, 2),
    ask DECIMAL(10, 2),
    vol DECIMAL(6, 4),
    delta DECIMAL(6, 4),
    gamma DECIMAL(6, 4),
    theta DECIMAL(6, 4),
    vega DECIMAL(6, 4),
    rho DECIMAL(6, 4),

    UNIQUE(date, ticker, expiration, strike, call_put)
);

CREATE TABLE spy_eod_options (
    id SERIAL PRIMARY KEY,
    quote_read_time TIMESTAMPTZ,
    underlying_last DECIMAL(10, 2),
    expire_date DATE,
    dte DECIMAL(10, 2),
    c_delta DECIMAL(10, 6),
    c_gamma DECIMAL(10, 6),
    c_vega DECIMAL(10, 6),
    c_theta DECIMAL(10, 6),
    c_rho DECIMAL(10, 6),
    c_iv DECIMAL(10, 6),
    c_volume INTEGER,
    c_last DECIMAL(10, 2),
    c_size VARCHAR(50),
    c_bid DECIMAL(10, 2),
    c_ask DECIMAL(10, 2),
    strike DECIMAL(10, 2),
    p_bid DECIMAL(10, 2),
    p_ask DECIMAL(10, 2),
    p_size VARCHAR(50),
    p_last DECIMAL(10, 2),
    p_delta DECIMAL(10, 6),
    p_gamma DECIMAL(10, 6),
    p_vega DECIMAL(10, 6),
    p_theta DECIMAL(10, 6),
    p_rho DECIMAL(10, 6),
    p_iv DECIMAL(10, 6),
    p_volume INTEGER,
    strike_distance DECIMAL(10, 2),
    strike_distance_pct DECIMAL(4, 3)
);

CREATE TABLE td_eod_options (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10),
    quote_date DATE,
    expiration DATE,
    strike FLOAT,
    call_put VARCHAR(4),
    open DECIMAL(10, 2),
    high DECIMAL(10, 2),
    low DECIMAL(10, 2),
    close DECIMAL(10, 2),
    volume INTEGER,
    bid DECIMAL(10, 2),
    ask DECIMAL(10, 2),
    delta FLOAT,
    gamma FLOAT,
    theta FLOAT,
    vega FLOAT,
    rho FLOAT,
    implied_vol FLOAT,
    iv_error FLOAT,
    d1 FLOAT,
    d2 FLOAT,
    color FLOAT,
    zomma FLOAT,
    speed FLOAT,
    epsilon FLOAT,
    lambda FLOAT,
    vomma FLOAT,
    vera FLOAT,
    veta FLOAT,
    ultima FLOAT,
    charm FLOAT,
    vanna FLOAT,
    dual_delta FLOAT,
    dual_gamma FLOAT,

    UNIQUE(quote_date, ticker, expiration, strike, call_put)
);
