services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-analysis-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - ASYNC_STOCK_ANALYSIS_DB=${ASYNC_STOCK_ANALYSIS_DB}
      - REDIS_URL=${REDIS_URL}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - FLOWER_URL=${FLOWER_URL}
      - PYTHONPATH=/app
      - BENZINGA_API_KEY=${BENZINGA_API_KEY}
      - FRED_API_KEY=${FRED_API_KEY}
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - stock-analysis-network

networks:
  stock-analysis-network:
    external: true